# Ejemplos básicos scikit-learn

In [2]:
# Cargar librerías
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split 
import pandas as pd

In [3]:
# Tipo breast_cancer
type(load_breast_cancer())

sklearn.utils._bunch.Bunch

In [4]:
# Cargar datos
data = load_breast_cancer()


In [5]:
# data es tipo Json (data:array y target:array)
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [6]:
# Solo quedarnos con data
    # pd.DataFrame(data.data)
pd.DataFrame(data['data'])

0      1       2       3   ...      26      27      28       29
0    17.99  10.38  122.80  1001.0  ...  0.7119  0.2654  0.4601  0.11890
1    20.57  17.77  132.90  1326.0  ...  0.2416  0.1860  0.2750  0.08902
2    19.69  21.25  130.00  1203.0  ...  0.4504  0.2430  0.3613  0.08758
3    11.42  20.38   77.58   386.1  ...  0.6869  0.2575  0.6638  0.17300
4    20.29  14.34  135.10  1297.0  ...  0.4000  0.1625  0.2364  0.07678
..     ...    ...     ...     ...  ...     ...     ...     ...      ...
564  21.56  22.39  142.00  1479.0  ...  0.4107  0.2216  0.2060  0.07115
565  20.13  28.25  131.20  1261.0  ...  0.3215  0.1628  0.2572  0.06637
566  16.60  28.08  108.30   858.1  ...  0.3403  0.1418  0.2218  0.07820
567  20.60  29.33  140.10  1265.0  ...  0.9387  0.2650  0.4087  0.12400
568   7.76  24.54   47.92   181.0  ...  0.0000  0.0000  0.2871  0.07039

[569 rows x 30 columns]

In [7]:
# Solo quedarnos con target
pd.DataFrame(data['target'])

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [8]:
# poner nombre a las columnas
pd.DataFrame(data['data'], columns=data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [9]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [10]:
len(data['data'])

569

In [11]:
# uso de train_test_lest: parte el conunto de datos
from sklearn.model_selection import train_test_split 
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None
)
    Split arrays or matrices into random train and test subsets.

    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value

In [12]:
# Se usan 70-80% datos para Entrenamiento (depende también del tamaño)
569*0.75

426.75

In [13]:
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'])


In [14]:
print(len(X_train))
print(len(X_test))
print(len(y_train)) 
print(len(y_test))

426
143
426
143


In [22]:
# siempre se pone el mismo random_state cuando se hacen las pruebas
# test_size el tamaño que es de test 20%
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=0.20, random_state=42)


In [23]:
print(len(X_train))
print(len(X_test))
print(len(y_train)) 
print(len(y_test))

455
114
455
114


In [30]:
# Ejemplo de uso de train_test_split con parámetros adicionales
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

data = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=0.20, random_state=42)
model = DecisionTreeClassifier(criterion='entropy', max_depth=4)

pred_2d = y_pred.reshape(len(y_pred), 1)
y_test_2d = y_test.reshape(len(y_test), 1)

df1 = pd.DataFrame(pred_2d, columns=['Predicciones'])
df2 = pd.DataFrame(y_test_2d, columns=['Valores Reales'])
df_final = pd.concat([df1, df2], axis=1)



In [47]:
# Ejemplo completo de uso Machine Learning(supervisado)
    # preprocesamiento (escalado tando para X_train y X_test)
    # entrenamiento
    # predicción
    # evaluar precisión
     
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=0.20, random_state=42)
model = DecisionTreeClassifier(criterion='entropy', max_depth=4) # Crear un clasificador de árbol de decisión con criterios específicos
model.fit(X_train, y_train) # entrenar el modelo con 80% datos
model.predict(X_test) # predecir con el modelo con 20% datos restantes
y_pred = model.predict(X_test) # guardar predicciones en y_pred
precision = accuracy_score(y_test, y_pred) # Calcular precisión comparando Predicciones vs Etiquetas
print(f'Precisión del modelo: {precision*100:.2f}%') 

df1 = pd.DataFrame(pred_2d, columns=['Predicciones'])
df2 = pd.DataFrame(y_test_2d, columns=['Valores Reales'])
df_final = pd.concat([df1,df2], axis=1)
print('Total pruebas: ' + str(len(df_final))) # distintas formas de imprimir en cadena +, con coma, f'
print('Numero de aciertos: ', len(df_final[df_final['Predicciones'] == df_final['Valores Reales']]))
print(f"Numero de fallos: {len(df_final[df_final['Predicciones'] != df_final['Valores Reales']])}")

Precisión del modelo: 95.61%
Total pruebas: 114
Numero de aciertos:  109
Numero de fallos: 5


In [48]:
# Prediciones del modelo
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [49]:
# Etiquetas (datos reales, del dataset)
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [50]:
# pasar las pred a columna
pred_2d = y_pred.reshape(len(y_pred),1)
pred_2d

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [51]:
y_test_2d = y_test.reshape(len(y_test),1)

In [52]:
# comparar Predicciones vs Valores Reales
import pandas as pd
df1 = pd.DataFrame(pred_2d, columns=['Predicciones'])
df2 = pd.DataFrame(y_test_2d, columns=['Valores Reales'])
df_final = pd.concat([df1,df2], axis=1)
df_final

Predicciones  Valores Reales
0               1               1
1               0               0
2               0               0
3               1               1
4               1               1
5               0               0
6               0               0
7               0               0
8               0               1
9               1               1
10              1               1
11              0               0
12              1               1
13              1               0
14              1               1
15              0               0
16              1               1
17              1               1
18              1               1
19              0               0
20              1               0
21              1               1
22              0               0
23              1               1
24              1               1
25              1               1
26              1               1
27              1               1
28              1               1
29              0               0
30              1               1
31              1               1
32              1               1
33              1               1
34              1               1
35              1               1
36              0               0
37              1               1
38              0               0
39              1               1
40              1               1
41              0               0
42              1               1
43              1               1
44              1               1
45              1               1
46              1               1
47              1               1
48              1               1
49              1               1
50              0               0
51              0               0
52              1               1
53              1               1
54              1               1
55              1               1
56              1               1
57              0               0
58              0               0
59              1               1
60              1               1
61              0               0
62              0               0
63              1               1
64              1               1
65              1               1
66              0               0
67              0               0
68              1               1
69              1               1
70              0               0
71              0               0
72              1               1
73              0               0
74              1               1
75              1               1
76              1               1
77              1               0
78              1               1
79              1               1
80              0               0
81              1               1
82              1               0
83              0               0
84              0               0
85              0               0
86              0               0
87              0               0
88              1               1
89              1               1
90              1               1
91              1               1
92              1               1
93              1               1
94              1               1
95              1               1
96              0               0
97              0               0
98              1               1
99              0               0
100             0               0
101             1               1
102             0               0
103             0               0
104             1               1
105             1               1
106             1               1
107             0               0
108             1               1
109             1               1
110             0               0
111             1               1
112             1               1
113             0               0

In [53]:
# para ver todo el DataFrame no comprimido (para comprobar los fallos de la predicción)
pd.set_option('display.max_rows', None)
print(df_final)

     Predicciones  Valores Reales
0               1               1
1               0               0
2               0               0
3               1               1
4               1               1
5               0               0
6               0               0
7               0               0
8               0               1
9               1               1
10              1               1
11              0               0
12              1               1
13              1               0
14              1               1
15              0               0
16              1               1
17              1               1
18              1               1
19              0               0
20              1               0
21              1               1
22              0               0
23              1               1
24              1               1
25              1               1
26              1               1
27              1               1
28            

In [54]:
# para ver donde falla la predicción
df_final[df_final['Predicciones'] != df_final['Valores Reales']]

Predicciones  Valores Reales
8              0               1
13             1               0
20             1               0
77             1               0
82             1               0

In [55]:
# hay mucha diferencia en los pesos de los valores,
# entonces puede haber unos que influyen más y otros menos
# Solución --> hacer un escalado de los datos
X_train

array([[9.029e+00, 1.733e+01, 5.879e+01, ..., 1.750e-01, 4.228e-01,
        1.175e-01],
       [2.109e+01, 2.657e+01, 1.427e+02, ..., 2.903e-01, 4.098e-01,
        1.284e-01],
       [9.173e+00, 1.386e+01, 5.920e+01, ..., 5.087e-02, 3.282e-01,
        8.490e-02],
       ...,
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02],
       [1.398e+01, 1.962e+01, 9.112e+01, ..., 1.827e-01, 3.179e-01,
        1.055e-01],
       [1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02]])

In [56]:
datos_inciales_sin_escalar = pd.DataFrame(data['data'], columns=data['feature_names'])

In [57]:
# Ejemplo completo de uso Machine Learning(supervisado)
    # Preprocesamiento => Esacala datos (tamaños distintos)
    # entrenamiento
    # predicción
    # evaluar precisión
     
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

data = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=0.20, random_state=42)
model = DecisionTreeClassifier(criterion='entropy', max_depth=4) # Crear un clasificador de árbol de decisión con criterios específicos
scaler = StandardScaler() # crear el objeto escalador
X_train = scaler.fit_transform(X_train) # ajustar y transformar los datos de entrenamiento
X_test = scaler.transform(X_test) # transformar los datos de prueba


model.fit(X_train, y_train) # entrenar el modelo con 80% datos
model.predict(X_test) # predecir con el modelo con 20% datos restantes
y_pred = model.predict(X_test) # guardar predicciones en y_pred
precision = accuracy_score(y_test, y_pred) # Calcular precisión comparando Predicciones vs Etiquetas
print(f'Precisión del modelo: {precision*100:.2f}%') 

df1 = pd.DataFrame(pred_2d, columns=['Predicciones'])
df2 = pd.DataFrame(y_test_2d, columns=['Valores Reales'])
df_final = pd.concat([df1,df2], axis=1)
print('Total pruebas: ' + str(len(df_final))) # distintas formas de imprimir en cadena +, con coma, f'
print('Numero de aciertos: ', len(df_final[df_final['Predicciones'] == df_final['Valores Reales']]))
print(f"Numero de fallos: {len(df_final[df_final['Predicciones'] != df_final['Valores Reales']])}")

Precisión del modelo: 94.74%
Total pruebas: 114
Numero de aciertos:  109
Numero de fallos: 5


In [58]:
# escalar es algo parecido a normalizar
# las y no porque eran 1 y 0

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) # fit + transform
X_test_scaled = scaler.transform(X_test)
X_train_scaled

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])